#!/usr/bin/env npx tsx
/**
 * Generate Demo SOG Assets
 *
 * Creates minimal placeholder PLY files for 3D Gaussian Splatting demos.
 * These are small, valid PLY files that can be loaded by the SplatViewer
 * without requiring external dependencies.
 *
 * Usage:
 *   pnpm generate:demo-assets
 *   npx tsx scripts/generate_demo_assets.ts
 *
 * Output:
 *   apps/web/public/demo/sog/
 *     ├── manifest.json
 *     ├── apartment-1.ply
 *     └── house-1.ply
 */

import * as fs from 'fs';
import * as path from 'path';

const OUTPUT_DIR = path.join(__dirname, '../apps/web/public/demo/sog');

interface Vertex {
  x: number;
  y: number;
  z: number;
  r: number;
  g: number;
  b: number;
  scale: [number, number, number];
  rotation: [number, number, number, number];
  opacity: number;
}

interface DemoTour {
  id: string;
  name: string;
  filename: string;
  thumbnail: string;
  description: string;
  vertices: Vertex[];
}

// Generate a simple cube of Gaussian splats
function generateCube(
  center: [number, number, number],
  size: number,
  color1: [number, number, number],
  color2: [number, number, number]
): Vertex[] {
  const half = size / 2;
  const vertices: Vertex[] = [];
  const offsets: [number, number, number][] = [
    [-1, -1, -1],
    [1, -1, -1],
    [1, 1, -1],
    [-1, 1, -1],
    [-1, -1, 1],
    [1, -1, 1],
    [1, 1, 1],
    [-1, 1, 1],
  ];

  for (let i = 0; i < offsets.length; i++) {
    const [ox, oy, oz] = offsets[i];
    const color = oz < 0 ? color1 : color2;
    vertices.push({
      x: center[0] + ox * half,
      y: center[1] + oy * half,
      z: center[2] + oz * half,
      r: color[0],
      g: color[1],
      b: color[2],
      scale: [0.1, 0.1, 0.1],
      rotation: [1, 0, 0, 0], // Identity quaternion
      opacity: 0.8,
    });
  }

  return vertices;
}

// Generate PLY file content
function generatePLY(vertices: Vertex[]): string {
  const header = `ply
format ascii 1.0
comment Demo 3DGS asset - generated by generate_demo_assets.ts
element vertex ${vertices.length}
property float x
property float y
property float z
property uchar red
property uchar green
property uchar blue
property float scale_0
property float scale_1
property float scale_2
property float rot_0
property float rot_1
property float rot_2
property float rot_3
property float opacity
end_header`;

  const data = vertices
    .map(
      (v) =>
        `${v.x} ${v.y} ${v.z} ${v.r} ${v.g} ${v.b} ${v.scale[0]} ${v.scale[1]} ${v.scale[2]} ${v.rotation[0]} ${v.rotation[1]} ${v.rotation[2]} ${v.rotation[3]} ${v.opacity}`
    )
    .join('\n');

  return `${header}\n${data}\n`;
}

// Demo tour definitions
const DEMO_TOURS: DemoTour[] = [
  {
    id: 'demo-apartment-1',
    name: 'Modern Apartment',
    filename: 'apartment-1.ply',
    thumbnail: 'apartment-1-thumb.jpg',
    description: 'A modern apartment showcase with open floor plan',
    vertices: generateCube([0, 0, 0], 2, [100, 150, 200], [120, 170, 220]),
  },
  {
    id: 'demo-house-1',
    name: 'Suburban House',
    filename: 'house-1.ply',
    thumbnail: 'house-1-thumb.jpg',
    description: 'A suburban family home with landscaped yard',
    vertices: generateCube([0, 0, 0.5], 3, [180, 140, 100], [140, 160, 140]),
  },
];

async function main() {
  console.log('🎨 Generating demo SOG assets...\n');

  // Ensure output directory exists
  if (!fs.existsSync(OUTPUT_DIR)) {
    fs.mkdirSync(OUTPUT_DIR, { recursive: true });
    console.log(`📁 Created directory: ${OUTPUT_DIR}`);
  }

  // Generate PLY files
  for (const tour of DEMO_TOURS) {
    const plyContent = generatePLY(tour.vertices);
    const outputPath = path.join(OUTPUT_DIR, tour.filename);
    fs.writeFileSync(outputPath, plyContent);
    const stats = fs.statSync(outputPath);
    console.log(`✅ Generated ${tour.filename} (${stats.size} bytes)`);
  }

  // Generate manifest
  const manifest = {
    version: '1.0.0',
    description: 'Demo 3DGS tour assets for RealRiches',
    generatedAt: new Date().toISOString(),
    tours: DEMO_TOURS.map((tour) => ({
      id: tour.id,
      name: tour.name,
      filename: tour.filename,
      thumbnail: tour.thumbnail,
      description: tour.description,
      sizeBytes: fs.statSync(path.join(OUTPUT_DIR, tour.filename)).size,
      status: 'generated',
    })),
    instructions:
      "Run 'pnpm generate:demo-assets' to regenerate these assets",
  };

  const manifestPath = path.join(OUTPUT_DIR, 'manifest.json');
  fs.writeFileSync(manifestPath, JSON.stringify(manifest, null, 2) + '\n');
  console.log(`✅ Generated manifest.json`);

  console.log('\n🎉 Demo assets generated successfully!');
  console.log(`   Output: ${OUTPUT_DIR}`);
  console.log(`   Tours: ${DEMO_TOURS.length}`);
}

main().catch((err) => {
  console.error('❌ Error generating demo assets:', err);
  process.exit(1);
});
